### ISSUE TITLE
ImportError: No module named numpy.lib.twodim_base

### ISSUE THREAD

**Issue by MutoAtum** [leson502/CORECT_EMNLP2023#1]
Hello Author! When i try to use "bash run_preprocess.sh" in Terminal, it will report an error" from numpy.lib.twodim_base import diag
ImportError: No module named numpy.lib.twodim_base".But it seems the sentence"from numpy.lib.twodim_base import diag" is unused import statement, how can i fix it? Thank you!
![RK4}(2KJJC5FJT~48J(3W7S](https://github.com/leson502/CORECT_EMNLP2023/assets/146109525/99ddaf99-4734-4bd1-afe9-63bff67de33e)
![(5~36N5(@D6S)CHI@ 6H{8C](https://github.com/leson502/CORECT_EMNLP2023/assets/146109525/e881afe1-cf2d-464c-9048-035f5210e28a)

**Comment by leson502** [comment]
thank you for reported, the commit 96ad0127f2e291e083e22440d002159e5f5c8b94 solved the issue

**Comment by MutoAtum** [comment]
> thank you for reported, the commit [96ad012](https://github.com/leson502/CORECT_EMNLP2023/commit/96ad0127f2e291e083e22440d002159e5f5c8b94) solved the issue

Thank you for your reply! I have successfully run through the code just now.
